personal_webhook = ""
discord_id = ""
super_debug = "yes"
cpu_or_gpu = "auto"
max_ips = "auto"
pyla_version = "0.5.6"
long_press_star_drop = "yes"
trophies_multiplier = 1
run_for_minutes = 600
current_emulator = "LDPlayer"
emulator_port = 5037