title = "Ranges"
shelly = [ 301.0, 490.0,]
colt = [ 324.0, 546.0,]
bull = [ 210.0, 341.0,]
brock = [ 354.0, 576.0,]
rico = [ 380.0, 618.0,]
spike = [ 301.0, 490.0,]
barley = [ 288.0, 469.0,]
jessie = [ 354.0, 576.0,]
nita = [ 236.0, 384.0,]
dynamike = [ 288.0, 469.0,]
elprimo = [ 0.0, 192.0,]
mortis = [ 0.0, 170.0,]
crow = [ 341.0, 554.0,]
poco = [ 275.0, 448.0,]
bo = [ 341.0, 554.0,]
piper = [ 393.0, 640.0,]
pam = [ 354.0, 576.0,]
tara = [ 315.0, 512.0,]
darryl = [ 236.0, 384.0,]
penny = [ 315.0, 512.0,]
frank = [ 236.0, 384.0,]
tick = [ 341.0, 554.0,]
leon = [ 380.0, 618.0,]
rosa = [ 0.0, 234.0,]
carl = [ 328.0, 533.0,]
bibi = [ 0.0, 234.0,]
8bit = [ 393.0, 640.0,]
sandy = [ 236.0, 384.0,]
bea = [ 393.0, 640.0,]
emz = [ 262.0, 426.0,]
mrp = [ 275.0, 448.0,]
max = [ 328.0, 533.0,]
jacky = [ 0.0, 213.0,]
gale = [ 328.0, 533.0,]
nani = [ 341.0, 554.0,]
sprout = [ 196.0, 320.0,]
surge = [ 262.0, 426.0,]
colette = [ 341.0, 554.0,]
amber = [ 328.0, 533.0,]
lou = [ 367.0, 597.0,]
byron = [ 393.0, 640.0,]
edgar = [ 0.0, 128.0,]
stu = [ 301.0, 490.0,]
belle = [ 393.0, 640.0,]
squeak = [ 301.0, 490.0,]
grom = [ 301.0, 490.0,]
buzz = [ 0.0, 170.0,]
griff = [ 328.0, 533.0,]
ash = [ 0.0, 298.0,]
meg = [ 354.0, 576.0,]
lola = [ 354.0, 576.0,]
fang = [ 0.0, 170.0,]
eve = [ 367.0, 597.0,]
janet = [ 0.0, 256.0,]
bonnie = [ 354.0, 576.0,]
otis = [ 354.0, 576.0,]
gus = [ 367.0, 597.0,]
buster = [ 210.0, 341.0,]
chester = [ 328.0, 533.0,]
gray = [ 354.0, 576.0,]
mandy = [ 354.0, 576.0,]
rt = [ 393.0, 640.0,]
willow = [ 288.0, 469.0,]
maisie = [ 341.0, 554.0,]
hank = [ 0.0, 213.0,]
cordelius = [ 210.0, 341.0,]
doug = [ 0.0, 213.0,]
pearl = [ 354.0, 576.0,]
chuck = [ 262.0, 426.0,]
charlie = [ 328.0, 533.0,]
mico = [ 0.0, 256.0,]
kit = [ 0.0, 234.0,]
melodie = [ 315.0, 512.0,]
angelo = [ 393.0, 640.0,]
draco = [ 0.0, 256.0,]
lily = [ 0.0, 128.0,]
berry = [ 249.0, 405.0,]
clancy = [ 301.0, 490.0,]
sam = [ 0.0, 192.0,]
moe = [ 196.0, 320.0,]
gene = [ 223.0, 362.0,]
ruffs = [ 354.0, 576.0,]
juju = [ 249.0, 405.0,]
shade = [ 0.0, 234.0,]
larrylawrie = [ 288.0, 469.0,]
kenji = [ 0.0, 234.0,]
ollie = [ 249.0, 405.0,]
meeple = [ 301.0, 490.0,]
finx = [ 328.0, 533.0,]
lumi = [ 341, 554,]
alli = [ 0, 192,]
kaze = [ 0, 170,]
jaeyong = [ 328, 533,]
trunk = [ 0, 213,]
ziggy = [ 288.0, 469.0,]
mina = [ 196, 512,]
gigi= [0, 149]
